import type { NextPage } from "next";
import { Flex } from "@chakra-ui/react";
import Head from "next/head";
import Login from "../src/pages/Login";

const LoginPage: NextPage = () => {
  return (
    <Flex w="100%" flexDir="column">
      <Head>
        <title>Bank Rut - Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Login />
    </Flex>
  );
};

export default LoginPage;
