import type { NextPage } from "next";
import { Flex } from "@chakra-ui/react";
import Head from "next/head";
import AccountInfo from "../../src/pages/AccountInfo";

const AccountInfoPage: NextPage = () => {
  return (
    <Flex w="100%" flexDir="column">
      <Head>
        <title>Bank Rut - Account Info</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AccountInfo />
    </Flex>
  );
};

export default AccountInfoPage;
