import type { NextPage } from "next";
import { Flex } from "@chakra-ui/react";
import Head from "next/head";
import RequestHistory from "../../src/pages/RequestHistory";

const RequestHistoryPage: NextPage = () => {
  return (
    <Flex w="100%" flexDir="column">
      <Head>
        <title>Bank Rut - Request History</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <RequestHistory />
    </Flex>
  );
};

export default RequestHistoryPage;
