import type { NextPage } from "next";
import { Flex } from "@chakra-ui/react";
import Head from "next/head";
import Transaction from "../../src/pages/Transaction";

const TransactionPage: NextPage = () => {
  return (
    <Flex w="100%" flexDir="column">
      <Head>
        <title>Bank Rut - Transaction</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Transaction />
    </Flex>
  );
};

export default TransactionPage;
