import type { NextPage } from "next";
import { Flex } from "@chakra-ui/react";
import Head from "next/head";
import TransactionHistory from "../../src/pages/TransactionHistory";

const TransactionHistoryPage: NextPage = () => {
  return (
    <Flex w="100%" flexDir="column">
      <Head>
        <title>Bank Rut - Transaction History</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TransactionHistory />
    </Flex>
  );
};

export default TransactionHistoryPage;
